[package]
name = "Event example"
version = "0.0.1"

[addresses]
std = "0x1"
aptos_framework = "0x1"
event = "0xc0e3685f993b18c4f6c1a4bdf7ed91144a58b225938486198ea1e80b740119b2"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

