[package]
name = "todo-list"
version = "1.0.0"
authors = []

[addresses]
advanced_todo_list_addr="0x42"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
