[package]
name = "Examples"
version = "1.0.0"

[addresses]
rewards_pool = "0x42"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
