[package]
name = "test_object"
version = "1.0.0"
authors = []

[addresses]
object = "0x42"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
