[package]
name = "Examples"
version = "0.0.0"

[addresses]
hello_blockchain = "0x788b6c6b019855c0c4be964ac6f978317af6848860450673912c486e0d21da91"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
